# # -*- makefile -*-

# MOSES_CODE=/fs/gna0/germann/code/mosesdecoder
# MOSES_ROOT=/fs/gna0/germann/moses
# LIBS = $(addprefix -l,moses icuuc icuio icui18n boost_iostreams)
# ibm1-align: ibm1-align.cc
# 	g++ -o $@ -L ${MOSES_ROOT}/lib -I ${MOSES_CODE} $^ ${LIBS} -ggdb