################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
util \
util/stream \
util/stream/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
util/double-conversion \
util/double-conversion/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
util/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
symal \
symal/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
search \
search/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
phrase-extract \
phrase-extract/pcfg-score \
phrase-extract/pcfg-score/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
phrase-extract/pcfg-extract \
phrase-extract/pcfg-extract/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
phrase-extract/pcfg-common \
phrase-extract/pcfg-common/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
phrase-extract/lexical-reordering \
phrase-extract/lexical-reordering/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
phrase-extract/extract-ghkm/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
phrase-extract/extract-ghkm \
phrase-extract/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
phrase-extract/bin/ScoreFeatureTest.test/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
moses-cmd \
moses-cmd/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
moses-chart-cmd \
moses-chart-cmd/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
moses/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
moses/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi/TranslationModel/fuzzy-match \
moses/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi/TranslationModel/Scope3Parser \
moses/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi/TranslationModel/RuleTable \
moses/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi/TranslationModel \
moses/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi/TranslationModel/DynSAInclude \
moses/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi/TranslationModel/CYKPlusParser \
moses \
moses/TranslationModel/fuzzy-match \
moses/TranslationModel/Scope3Parser \
moses/TranslationModel/RuleTable \
moses/TranslationModel \
moses/TranslationModel/DynSAInclude \
moses/TranslationModel/CompactPT/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
moses/TranslationModel/CompactPT \
moses/TranslationModel/CYKPlusParser \
moses/LM/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
moses/LM/bin/BackwardTest.test/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
moses/LM \
misc \
misc/pmoses \
misc/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
mira/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
mira \
mert \
mert/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
mert/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi/TER \
mert/TER \
lm \
lm/filter \
lm/filter/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
lm/builder \
lm/builder/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
lm/bin/partial_test.test/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
lm/bin/model_test.test/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
lm/bin/left_test.test/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
lm/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
jam-files/engine \
jam-files/engine/modules \
contrib/sigtest-filter \
contrib/server \
contrib/server/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
contrib/relent-filter/src \
contrib/relent-filter/sigtest-filter \
contrib/python/moses \
contrib/memscore \
contrib/lmserver \
contrib/lmserver/examples \
contrib/eppex \
contrib/checkplf \
biconcor/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \
biconcor \
OnDiskPt \
OnDiskPt/bin/gcc-4.7.2/release/debug-symbols-on/link-static/threading-multi \

