#!/bin/bash
set -e
self="$(readlink -f "$0")"
if 
  which bjam >/dev/null 2>/dev/null && #Have a bjam in path
  [ "$self" != "$(readlink -f "$(which bjam)")" ] && #bjam in path isn't this script
  bjam --help >/dev/null 2>/dev/null #bjam in path isn't broken (i.e. has boost-build)
then
  #Delegate to system bjam
  exec bjam "$@"
fi

top="$(dirname "$0")"
if [ ! -x "$top"/jam-files/bjam ]; then
  pushd "$top/jam-files/engine"
  ./build.sh
  cp -f bin.*/bjam ../bjam
  popd
fi

export BOOST_BUILD_PATH="$top"/jam-files/boost-build 
exec "$top"/jam-files/bjam "$@"
