#!/bin/bash
set -e
if
  bjam="$(which bjam 2>/dev/null)" && #exists
  [ ${#bjam} != 0 ] && #paranoia about which printing nothing then returning true
  ! grep UFIHGUFIHBDJKNCFZXAEVA "${bjam}" </dev/null >/dev/null && #bjam in path isn't this script
  "${bjam}" --help >/dev/null 2>/dev/null && #bjam in path isn't broken (i.e. has boost-build)
  "${bjam}" --version |grep "Boost.Build 201" >/dev/null 2>/dev/null #It's recent enough.  
then
  #Delegate to system bjam
  exec "${bjam}" "$@"
fi

top="$(dirname "$0")"
if [ ! -x "$top"/jam-files/bjam ]; then
  pushd "$top/jam-files/engine"
  ./build.sh
  cp -f bin.*/bjam ../bjam
  popd
fi

export BOOST_BUILD_PATH="$top"/jam-files/boost-build 
exec "$top"/jam-files/bjam "$@"
