#!/bin/bash
#Moses used to run autotools.  This helps people migrate to bjam by deleting files that it generated.  Run it in the top-level directory.  
while read a; do
  rm -rf $a
done <<EOF
Makefile
Makefile.in
OnDiskPt/src/
aclocal.m4
autom4te.cache/
config.guess
config.h
config.log
config.status
config.sub
configure
depcomp
install-sh
libtool
lm/.deps/
lm/.libs/
lm/Makefile
lm/Makefile.in
lm/bhiksha.lo
lm/bhiksha.o
lm/binary_format.lo
lm/binary_format.o
lm/build_binary.o
lm/config.lo
lm/config.o
lm/libkenlm.la
lm/lm_exception.lo
lm/lm_exception.o
lm/model.lo
lm/model.o
lm/ngram_query.o
lm/quantize.lo
lm/quantize.o
lm/read_arpa.lo
lm/read_arpa.o
lm/search_hashed.lo
lm/search_hashed.o
lm/search_trie.lo
lm/search_trie.o
lm/trie.lo
lm/trie.o
lm/trie_sort.lo
lm/trie_sort.o
lm/virtual_interface.lo
lm/virtual_interface.o
lm/vocab.lo
lm/vocab.o
ltmain.sh
m4/
mert/.deps/
mert/Makefile
mert/Makefile.in
misc/.deps/
misc/Makefile
misc/Makefile.in
missing
moses-chart-cmd/src/.deps/
moses-chart-cmd/src/Makefile
moses-chart-cmd/src/Makefile.in
moses-cmd/src/.deps/
moses-cmd/src/Makefile
moses-cmd/src/Makefile.in
moses/src/.deps/
moses/src/AlignmentInfo.lo
moses/src/AlignmentInfo.o
moses/src/AlignmentInfoCollection.lo
moses/src/AlignmentInfoCollection.o
moses/src/Base.lo
moses/src/Base.o
moses/src/BilingualDynSuffixArray.lo
moses/src/BilingualDynSuffixArray.o
moses/src/BitmapContainer.lo
moses/src/BitmapContainer.o
moses/src/ChartCell.lo
moses/src/ChartCell.o
moses/src/ChartCellCollection.lo
moses/src/ChartCellCollection.o
moses/src/ChartHypothesis.lo
moses/src/ChartHypothesis.o
moses/src/ChartHypothesisCollection.lo
moses/src/ChartHypothesisCollection.o
moses/src/ChartManager.lo
moses/src/ChartManager.o
moses/src/ChartRuleLookupManager.lo
moses/src/ChartRuleLookupManager.o
moses/src/ChartRuleLookupManagerMemory.lo
moses/src/ChartRuleLookupManagerMemory.o
moses/src/ChartRuleLookupManagerOnDisk.lo
moses/src/ChartRuleLookupManagerOnDisk.o
moses/src/ChartTranslationOption.lo
moses/src/ChartTranslationOption.o
moses/src/ChartTranslationOptionCollection.lo
moses/src/ChartTranslationOptionCollection.o
moses/src/ChartTranslationOptionList.lo
moses/src/ChartTranslationOptionList.o
moses/src/ChartTrellisDetour.lo
moses/src/ChartTrellisDetour.o
moses/src/ChartTrellisDetourQueue.lo
moses/src/ChartTrellisDetourQueue.o
moses/src/ChartTrellisNode.lo
moses/src/ChartTrellisNode.o
moses/src/ChartTrellisPath.lo
moses/src/ChartTrellisPath.o
moses/src/ConfusionNet.lo
moses/src/ConfusionNet.o
moses/src/DecodeFeature.lo
moses/src/DecodeFeature.o
moses/src/DecodeGraph.lo
moses/src/DecodeGraph.o
moses/src/DecodeStep.lo
moses/src/DecodeStep.o
moses/src/DecodeStepGeneration.lo
moses/src/DecodeStepGeneration.o
moses/src/DecodeStepTranslation.lo
moses/src/DecodeStepTranslation.o
moses/src/Dictionary.lo
moses/src/Dictionary.o
moses/src/DotChart.lo
moses/src/DotChart.o
moses/src/DotChartInMemory.lo
moses/src/DotChartInMemory.o
moses/src/DotChartOnDisk.lo
moses/src/DotChartOnDisk.o
moses/src/DummyScoreProducers.lo
moses/src/DummyScoreProducers.o
moses/src/DynSuffixArray.lo
moses/src/DynSuffixArray.o
moses/src/FFState.lo
moses/src/FFState.o
moses/src/Factor.lo
moses/src/Factor.o
moses/src/FactorCollection.lo
moses/src/FactorCollection.o
moses/src/FactorTypeSet.lo
moses/src/FactorTypeSet.o
moses/src/Factory.lo
moses/src/Factory.o
moses/src/FeatureFunction.lo
moses/src/FeatureFunction.o
moses/src/FloydWarshall.lo
moses/src/FloydWarshall.o
moses/src/GenerationDictionary.lo
moses/src/GenerationDictionary.o
moses/src/GlobalLexicalModel.lo
moses/src/GlobalLexicalModel.o
moses/src/Hypothesis.lo
moses/src/Hypothesis.o
moses/src/HypothesisStack.lo
moses/src/HypothesisStack.o
moses/src/HypothesisStackCubePruning.lo
moses/src/HypothesisStackCubePruning.o
moses/src/HypothesisStackNormal.lo
moses/src/HypothesisStackNormal.o
moses/src/Implementation.lo
moses/src/Implementation.o
moses/src/InputFileStream.lo
moses/src/InputFileStream.o
moses/src/InputType.lo
moses/src/InputType.o
moses/src/Joint.lo
moses/src/Joint.o
moses/src/Ken.lo
moses/src/Ken.o
moses/src/LMList.lo
moses/src/LMList.o
moses/src/LVoc.lo
moses/src/LVoc.o
moses/src/LexicalReordering.lo
moses/src/LexicalReordering.o
moses/src/LexicalReorderingState.lo
moses/src/LexicalReorderingState.o
moses/src/LexicalReorderingTable.lo
moses/src/LexicalReorderingTable.o
moses/src/Makefile
moses/src/Makefile.in
moses/src/Manager.lo
moses/src/Manager.o
moses/src/MultiFactor.lo
moses/src/MultiFactor.o
moses/src/PCNTools.lo
moses/src/PCNTools.o
moses/src/Parameter.lo
moses/src/Parameter.o
moses/src/PartialTranslOptColl.lo
moses/src/PartialTranslOptColl.o
moses/src/Phrase.lo
moses/src/Phrase.o
moses/src/PhraseDictionary.lo
moses/src/PhraseDictionary.o
moses/src/PhraseDictionaryALSuffixArray.lo
moses/src/PhraseDictionaryALSuffixArray.o
moses/src/PhraseDictionaryDynSuffixArray.lo
moses/src/PhraseDictionaryDynSuffixArray.o
moses/src/PhraseDictionaryHiero.lo
moses/src/PhraseDictionaryHiero.o
moses/src/PhraseDictionaryMemory.lo
moses/src/PhraseDictionaryMemory.o
moses/src/PhraseDictionaryNode.lo
moses/src/PhraseDictionaryNode.o
moses/src/PhraseDictionaryNodeSCFG.lo
moses/src/PhraseDictionaryNodeSCFG.o
moses/src/PhraseDictionaryOnDisk.lo
moses/src/PhraseDictionaryOnDisk.o
moses/src/PhraseDictionarySCFG.lo
moses/src/PhraseDictionarySCFG.o
moses/src/PhraseDictionaryTree.lo
moses/src/PhraseDictionaryTree.o
moses/src/PhraseDictionaryTreeAdaptor.lo
moses/src/PhraseDictionaryTreeAdaptor.o
moses/src/PrefixTreeMap.lo
moses/src/PrefixTreeMap.o
moses/src/Remote.lo
moses/src/Remote.o
moses/src/ReorderingConstraint.lo
moses/src/ReorderingConstraint.o
moses/src/ReorderingStack.lo
moses/src/ReorderingStack.o
moses/src/RuleCube.lo
moses/src/RuleCube.o
moses/src/RuleCubeItem.lo
moses/src/RuleCubeItem.o
moses/src/RuleCubeQueue.lo
moses/src/RuleCubeQueue.o
moses/src/RuleTableLoaderCompact.lo
moses/src/RuleTableLoaderCompact.o
moses/src/RuleTableLoaderFactory.lo
moses/src/RuleTableLoaderFactory.o
moses/src/RuleTableLoaderHiero.lo
moses/src/RuleTableLoaderHiero.o
moses/src/RuleTableLoaderStandard.lo
moses/src/RuleTableLoaderStandard.o
moses/src/ScoreComponentCollection.lo
moses/src/ScoreComponentCollection.o
moses/src/ScoreIndexManager.lo
moses/src/ScoreIndexManager.o
moses/src/ScoreProducer.lo
moses/src/ScoreProducer.o
moses/src/Search.lo
moses/src/Search.o
moses/src/SearchCubePruning.lo
moses/src/SearchCubePruning.o
moses/src/SearchNormal.lo
moses/src/SearchNormal.o
moses/src/Sentence.lo
moses/src/Sentence.o
moses/src/SentenceStats.lo
moses/src/SentenceStats.o
moses/src/SingleFactor.lo
moses/src/SingleFactor.o
moses/src/SquareMatrix.lo
moses/src/SquareMatrix.o
moses/src/TargetPhrase.lo
moses/src/TargetPhrase.o
moses/src/TargetPhraseCollection.lo
moses/src/TargetPhraseCollection.o
moses/src/ThreadPool.lo
moses/src/ThreadPool.o
moses/src/Timer.lo
moses/src/Timer.o
moses/src/TranslationOption.lo
moses/src/TranslationOption.o
moses/src/TranslationOptionCollection.lo
moses/src/TranslationOptionCollection.o
moses/src/TranslationOptionCollectionConfusionNet.lo
moses/src/TranslationOptionCollectionConfusionNet.o
moses/src/TranslationOptionCollectionText.lo
moses/src/TranslationOptionCollectionText.o
moses/src/TranslationOptionList.lo
moses/src/TranslationOptionList.o
moses/src/TranslationSystem.lo
moses/src/TranslationSystem.o
moses/src/file.lo
moses/src/file.o
moses/src/hash.lo
moses/src/hash.o
moses/src/vocab.lo
moses/src/vocab.o
scripts/ems/biconcor/Alignment.o
scripts/ems/biconcor/Mismatch.o
scripts/ems/biconcor/PhrasePair.o
scripts/ems/biconcor/PhrasePairCollection.o
scripts/ems/biconcor/SuffixArray.o
scripts/ems/biconcor/TargetCorpus.o
scripts/ems/biconcor/Vocabulary.o
scripts/ems/biconcor/base64.o
scripts/ems/biconcor/biconcor.o
scripts/training/compact-rule-table/config.log
scripts/training/compact-rule-table/config.status
scripts/training/eppex/
scripts/training/lexical-reordering/reordering_classes.o
scripts/training/memscore/
scripts/training/phrase-extract/AlignmentPhrase.o
scripts/training/phrase-extract/ExtractedRule.o
scripts/training/phrase-extract/HoleCollection.o
scripts/training/phrase-extract/InputFileStream.o
scripts/training/phrase-extract/PhraseAlignment.o
scripts/training/phrase-extract/SentenceAlignment.o
scripts/training/phrase-extract/SentenceAlignmentWithSyntax.o
scripts/training/phrase-extract/SyntaxTree.o
scripts/training/phrase-extract/XmlTree.o
scripts/training/phrase-extract/consolidate-direct.o
scripts/training/phrase-extract/consolidate-reverse.o
scripts/training/phrase-extract/consolidate.o
scripts/training/phrase-extract/extract-lex.o
scripts/training/phrase-extract/extract-rules.o
scripts/training/phrase-extract/extract.o
scripts/training/phrase-extract/relax-parse.o
scripts/training/phrase-extract/score.o
scripts/training/phrase-extract/statistics.o
scripts/training/phrase-extract/tables-core.o
scripts/training/symal/cmd.o
stamp-h1
util/.deps/
util/.libs/
util/Makefile
util/Makefile.in
util/bit_packing.lo
util/bit_packing.o
util/ersatz_progress.lo
util/ersatz_progress.o
util/exception.lo
util/exception.o
util/file.lo
util/file.o
util/file_piece.lo
util/file_piece.o
util/libkenutil.la
util/mmap.lo
util/mmap.o
util/murmur_hash.lo
util/murmur_hash.o
EOF
