extract-ghkm.o: extract-ghkm.cpp Alignment.h AlignmentGraph.h ParseTree.h \
  Span.h Rule.h Exception.h XmlTreeParser.h
Alignment.o: Alignment.cpp Alignment.h Exception.h
AlignmentGraph.o: AlignmentGraph.cpp AlignmentGraph.h Alignment.h \
  ParseTree.h Span.h Rule.h Subgraph.h
ParseTree.o: ParseTree.cpp ParseTree.h
Span.o: Span.cpp Span.h
Subgraph.o: Subgraph.cpp Subgraph.h AlignmentGraph.h Alignment.h \
  ParseTree.h Span.h Rule.h
SyntaxTree.o: ../SyntaxTree.cpp ../SyntaxTree.h
XmlTree.o: ../XmlTree.cpp ../SyntaxTree.h
XmlTreeParser.o: XmlTreeParser.cpp XmlTreeParser.h ParseTree.h \
  ../XmlTree.h ../SyntaxTree.h
