#!/usr/bin/perl
$x=0;
while (<>) {
  chomp;

  if (/^Finished loading LanguageModels/) {
    my $time = get_time($_);
    print "LMLOAD_TIME ~ $time\n";
  }
  if (/^Finished loading phrase tables/) {
    my $time = get_time($_);
    print "PTLOAD_TIME ~ $time\n";
  }
  next unless /^BEST HYPO:/;
  my $pscore = "FORMAT ERROR";
  # BEST HYPO: only then will the european institutions to your task . [11111111111]  [-3.65,0.00,-12.34,-8.00,-10.00,0.00,-14.39]
  if (/\[1+\]\s*\[[^\]]*,\s*(-?\d+\.\d+)\]/) {
    $pscore = $1;
  }
  $x++;
  print "SCORE_$x = $pscore\n";
}

sub get_time {
  my $time = shift;
  my $res = "FORMAT ERROR";
  if ($time =~ /\[(\d+\.\d+)\]\s*seconds*/) {
    $res = $1;
  }
  return $res;
}
