/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class QueryPt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public QueryPt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(QueryPt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigQueryPtJNI.delete_QueryPt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QueryPt(String path) {
    this(SwigQueryPtJNI.new_QueryPt(path), true);
  }

  public String query(String phrase) {
    return SwigQueryPtJNI.QueryPt_query(swigCPtr, this, phrase);
  }

}
