/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SwigQueryPtJNI {
  public final static native long new_QueryPt(String jarg1, int jarg2);
  public final static native String QueryPt_query(long jarg1, QueryPt jarg1_, String jarg2);
  public final static native void delete_QueryPt(long jarg1);
}
