#! /bin/sh -w
bin=$1; shift
testdir=$1; shift
cd $testdir

extractor=$bin/extractor

size=15

ref=data/reference

prevscfile=""
prevffile=""

for run in 1 2 3 4 5 ; do
nbest=data/nbest.$run.gz
scfile=SCORESTAT.run$run
ffile=FEATSTAT.run$run

if [ $run -le 1 ] ;then
$extractor --nbest $nbest --reference $ref --ffile $ffile --scfile $scfile
$extractor --binary --nbest $nbest --reference $ref --ffile $ffile.b --scfile $scfile.b
$extractor --ffile $ffile.2 --scfile $scfile.2 --prev-scfile $scfile.b --prev-ffile $ffile.b
else
$extractor --nbest $nbest --reference $ref --ffile $ffile --scfile $scfile --prev-scfile $prevscfile --prev-ffile $prevffile
$extractor --binary --nbest $nbest --reference $ref --ffile $ffile.b --scfile $scfile.b --prev-scfile $prevscfile.b --prev-ffile $prevffile.b
$extractor --ffile $ffile.2 --scfile $scfile.2 --prev-scfile $scfile.b --prev-ffile $ffile.b
fi


cmp $scfile $scfile.2 
cmp $ffile $ffile.2 
wc $ffile $scfile $ffile.2 $scfile.2 | grep run | perl -pe 's/ +/ /g;s/^ //;'

prevscfile=$scfile
prevffile=$ffile

run=$(($run +1))
done


for run in 1 2 3 4 5 ; do
scfile=SCORESTAT.run$run
ffile=FEATSTAT.run$run

rm $ffile $scfile
rm $ffile.2 $scfile.2
done
