#!/usr/bin/perl

BEGIN {push @INC, "tests/perllib";} #expect we'll be called from regression-testing/
use RegTestUtils;

$x=0;
while (<>) {
  chomp;

  if (/^Finished loading LanguageModels/) {
    my $time = RegTestUtils::readTime($_);
    print "LMLOAD_TIME ~ $time\n";
  }
  if (/^Finished loading phrase tables/) {
    my $time = RegTestUtils::readTime($_);
    print "PTLOAD_TIME ~ $time\n";
  }
  next unless /^BEST HYPO:/;
  my $pscore = RegTestUtils::readHypoScore($_);
  $x++;
  print "SCORE_$x = $pscore\n";
}
