#! /bin/sh -w

bin=$1; shift
testdir=$1; shift
cd $testdir

extractor=$bin/extractor

size=15

ref=data/reference

prevscfile=""
prevffile=""

for run in 1 2 3 4 5 ; do
nbest=data/nbest.$run.gz
scfile=SCORESTAT.run$run
ffile=FEATSTAT.run$run

if [ $run -le 1 ] ;then
$extractor --nbest $nbest --reference $ref --ffile $ffile --scfile $scfile
else
$extractor --nbest $nbest --reference $ref --ffile $ffile --scfile $scfile --prev-scfile $prevscfile --prev-ffile $prevffile
fi

prevscfile=$scfile
prevffile=$ffile

cat $ffile $scfile

run=$(($run +1))
done

for run in 1 2 3 4 5 ; do
scfile=SCORESTAT.run$run
ffile=FEATSTAT.run$run

rm $ffile $scfile
done
