################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../moses/AlignmentInfo.cpp \
../moses/AlignmentInfoCollection.cpp \
../moses/AlignmentInfoTest.cpp \
../moses/BitmapContainer.cpp \
../moses/BleuScoreFeature.cpp \
../moses/CacheBasedLanguageModel.cpp \
../moses/ChartCell.cpp \
../moses/ChartCellCollection.cpp \
../moses/ChartHypothesis.cpp \
../moses/ChartHypothesisCollection.cpp \
../moses/ChartManager.cpp \
../moses/ChartParser.cpp \
../moses/ChartTranslationOptionList.cpp \
../moses/ChartTranslationOptions.cpp \
../moses/ChartTrellisDetour.cpp \
../moses/ChartTrellisDetourQueue.cpp \
../moses/ChartTrellisNode.cpp \
../moses/ChartTrellisPath.cpp \
../moses/ConfusionNet.cpp \
../moses/DecodeFeature.cpp \
../moses/DecodeGraph.cpp \
../moses/DecodeStep.cpp \
../moses/DecodeStepGeneration.cpp \
../moses/DecodeStepTranslation.cpp \
../moses/Dictionary.cpp \
../moses/DummyScoreProducers.cpp \
../moses/FFState.cpp \
../moses/Factor.cpp \
../moses/FactorCollection.cpp \
../moses/FactorTypeSet.cpp \
../moses/FeatureFunction.cpp \
../moses/FeatureVector.cpp \
../moses/FeatureVectorTest.cpp \
../moses/File.cpp \
../moses/FloydWarshall.cpp \
../moses/GenerationDictionary.cpp \
../moses/GlobalLexicalModel.cpp \
../moses/GlobalLexicalModelUnlimited.cpp \
../moses/Hildreth.cpp \
../moses/Hypothesis.cpp \
../moses/HypothesisStack.cpp \
../moses/HypothesisStackCubePruning.cpp \
../moses/HypothesisStackNormal.cpp \
../moses/Incremental.cpp \
../moses/InputFileStream.cpp \
../moses/InputType.cpp \
../moses/LMList.cpp \
../moses/LVoc.cpp \
../moses/LexicalReordering.cpp \
../moses/LexicalReorderingState.cpp \
../moses/LexicalReorderingTable.cpp \
../moses/Manager.cpp \
../moses/MiraOptimiser.cpp \
../moses/MockHypothesis.cpp \
../moses/MosesTest.cpp \
../moses/NonTerminal.cpp \
../moses/OnlineLearner.cpp \
../moses/PCNTools.cpp \
../moses/Parameter.cpp \
../moses/PartialTranslOptColl.cpp \
../moses/Phrase.cpp \
../moses/PhraseBoundaryFeature.cpp \
../moses/PhraseLengthFeature.cpp \
../moses/PhraseLengthFeatureTest.cpp \
../moses/PhrasePairFeature.cpp \
../moses/PrefixTreeMap.cpp \
../moses/ReorderingConstraint.cpp \
../moses/ReorderingStack.cpp \
../moses/RuleCube.cpp \
../moses/RuleCubeItem.cpp \
../moses/RuleCubeQueue.cpp \
../moses/ScoreComponentCollection.cpp \
../moses/ScoreComponentCollectionTest.cpp \
../moses/ScoreProducer.cpp \
../moses/Search.cpp \
../moses/SearchCubePruning.cpp \
../moses/SearchNormal.cpp \
../moses/SearchNormalBatch.cpp \
../moses/Sentence.cpp \
../moses/SentenceStats.cpp \
../moses/SourceWordDeletionFeature.cpp \
../moses/SparsePhraseDictionaryFeature.cpp \
../moses/SquareMatrix.cpp \
../moses/StaticData.cpp \
../moses/SyntacticLanguageModel.cpp \
../moses/TargetBigramFeature.cpp \
../moses/TargetBigramFeatureTest.cpp \
../moses/TargetNgramFeature.cpp \
../moses/TargetPhrase.cpp \
../moses/TargetPhraseCollection.cpp \
../moses/TargetWordInsertionFeature.cpp \
../moses/ThreadPool.cpp \
../moses/Timer.cpp \
../moses/TranslationOption.cpp \
../moses/TranslationOptionCollection.cpp \
../moses/TranslationOptionCollectionConfusionNet.cpp \
../moses/TranslationOptionCollectionText.cpp \
../moses/TranslationOptionList.cpp \
../moses/TranslationSystem.cpp \
../moses/TreeInput.cpp \
../moses/TrellisPath.cpp \
../moses/TrellisPathCollection.cpp \
../moses/UserMessage.cpp \
../moses/Util.cpp \
../moses/Word.cpp \
../moses/WordLattice.cpp \
../moses/WordTranslationFeature.cpp \
../moses/WordsBitmap.cpp \
../moses/WordsRange.cpp \
../moses/XmlOption.cpp 

OBJS += \
./moses/AlignmentInfo.o \
./moses/AlignmentInfoCollection.o \
./moses/AlignmentInfoTest.o \
./moses/BitmapContainer.o \
./moses/BleuScoreFeature.o \
./moses/CacheBasedLanguageModel.o \
./moses/ChartCell.o \
./moses/ChartCellCollection.o \
./moses/ChartHypothesis.o \
./moses/ChartHypothesisCollection.o \
./moses/ChartManager.o \
./moses/ChartParser.o \
./moses/ChartTranslationOptionList.o \
./moses/ChartTranslationOptions.o \
./moses/ChartTrellisDetour.o \
./moses/ChartTrellisDetourQueue.o \
./moses/ChartTrellisNode.o \
./moses/ChartTrellisPath.o \
./moses/ConfusionNet.o \
./moses/DecodeFeature.o \
./moses/DecodeGraph.o \
./moses/DecodeStep.o \
./moses/DecodeStepGeneration.o \
./moses/DecodeStepTranslation.o \
./moses/Dictionary.o \
./moses/DummyScoreProducers.o \
./moses/FFState.o \
./moses/Factor.o \
./moses/FactorCollection.o \
./moses/FactorTypeSet.o \
./moses/FeatureFunction.o \
./moses/FeatureVector.o \
./moses/FeatureVectorTest.o \
./moses/File.o \
./moses/FloydWarshall.o \
./moses/GenerationDictionary.o \
./moses/GlobalLexicalModel.o \
./moses/GlobalLexicalModelUnlimited.o \
./moses/Hildreth.o \
./moses/Hypothesis.o \
./moses/HypothesisStack.o \
./moses/HypothesisStackCubePruning.o \
./moses/HypothesisStackNormal.o \
./moses/Incremental.o \
./moses/InputFileStream.o \
./moses/InputType.o \
./moses/LMList.o \
./moses/LVoc.o \
./moses/LexicalReordering.o \
./moses/LexicalReorderingState.o \
./moses/LexicalReorderingTable.o \
./moses/Manager.o \
./moses/MiraOptimiser.o \
./moses/MockHypothesis.o \
./moses/MosesTest.o \
./moses/NonTerminal.o \
./moses/OnlineLearner.o \
./moses/PCNTools.o \
./moses/Parameter.o \
./moses/PartialTranslOptColl.o \
./moses/Phrase.o \
./moses/PhraseBoundaryFeature.o \
./moses/PhraseLengthFeature.o \
./moses/PhraseLengthFeatureTest.o \
./moses/PhrasePairFeature.o \
./moses/PrefixTreeMap.o \
./moses/ReorderingConstraint.o \
./moses/ReorderingStack.o \
./moses/RuleCube.o \
./moses/RuleCubeItem.o \
./moses/RuleCubeQueue.o \
./moses/ScoreComponentCollection.o \
./moses/ScoreComponentCollectionTest.o \
./moses/ScoreProducer.o \
./moses/Search.o \
./moses/SearchCubePruning.o \
./moses/SearchNormal.o \
./moses/SearchNormalBatch.o \
./moses/Sentence.o \
./moses/SentenceStats.o \
./moses/SourceWordDeletionFeature.o \
./moses/SparsePhraseDictionaryFeature.o \
./moses/SquareMatrix.o \
./moses/StaticData.o \
./moses/SyntacticLanguageModel.o \
./moses/TargetBigramFeature.o \
./moses/TargetBigramFeatureTest.o \
./moses/TargetNgramFeature.o \
./moses/TargetPhrase.o \
./moses/TargetPhraseCollection.o \
./moses/TargetWordInsertionFeature.o \
./moses/ThreadPool.o \
./moses/Timer.o \
./moses/TranslationOption.o \
./moses/TranslationOptionCollection.o \
./moses/TranslationOptionCollectionConfusionNet.o \
./moses/TranslationOptionCollectionText.o \
./moses/TranslationOptionList.o \
./moses/TranslationSystem.o \
./moses/TreeInput.o \
./moses/TrellisPath.o \
./moses/TrellisPathCollection.o \
./moses/UserMessage.o \
./moses/Util.o \
./moses/Word.o \
./moses/WordLattice.o \
./moses/WordTranslationFeature.o \
./moses/WordsBitmap.o \
./moses/WordsRange.o \
./moses/XmlOption.o 

CPP_DEPS += \
./moses/AlignmentInfo.d \
./moses/AlignmentInfoCollection.d \
./moses/AlignmentInfoTest.d \
./moses/BitmapContainer.d \
./moses/BleuScoreFeature.d \
./moses/CacheBasedLanguageModel.d \
./moses/ChartCell.d \
./moses/ChartCellCollection.d \
./moses/ChartHypothesis.d \
./moses/ChartHypothesisCollection.d \
./moses/ChartManager.d \
./moses/ChartParser.d \
./moses/ChartTranslationOptionList.d \
./moses/ChartTranslationOptions.d \
./moses/ChartTrellisDetour.d \
./moses/ChartTrellisDetourQueue.d \
./moses/ChartTrellisNode.d \
./moses/ChartTrellisPath.d \
./moses/ConfusionNet.d \
./moses/DecodeFeature.d \
./moses/DecodeGraph.d \
./moses/DecodeStep.d \
./moses/DecodeStepGeneration.d \
./moses/DecodeStepTranslation.d \
./moses/Dictionary.d \
./moses/DummyScoreProducers.d \
./moses/FFState.d \
./moses/Factor.d \
./moses/FactorCollection.d \
./moses/FactorTypeSet.d \
./moses/FeatureFunction.d \
./moses/FeatureVector.d \
./moses/FeatureVectorTest.d \
./moses/File.d \
./moses/FloydWarshall.d \
./moses/GenerationDictionary.d \
./moses/GlobalLexicalModel.d \
./moses/GlobalLexicalModelUnlimited.d \
./moses/Hildreth.d \
./moses/Hypothesis.d \
./moses/HypothesisStack.d \
./moses/HypothesisStackCubePruning.d \
./moses/HypothesisStackNormal.d \
./moses/Incremental.d \
./moses/InputFileStream.d \
./moses/InputType.d \
./moses/LMList.d \
./moses/LVoc.d \
./moses/LexicalReordering.d \
./moses/LexicalReorderingState.d \
./moses/LexicalReorderingTable.d \
./moses/Manager.d \
./moses/MiraOptimiser.d \
./moses/MockHypothesis.d \
./moses/MosesTest.d \
./moses/NonTerminal.d \
./moses/OnlineLearner.d \
./moses/PCNTools.d \
./moses/Parameter.d \
./moses/PartialTranslOptColl.d \
./moses/Phrase.d \
./moses/PhraseBoundaryFeature.d \
./moses/PhraseLengthFeature.d \
./moses/PhraseLengthFeatureTest.d \
./moses/PhrasePairFeature.d \
./moses/PrefixTreeMap.d \
./moses/ReorderingConstraint.d \
./moses/ReorderingStack.d \
./moses/RuleCube.d \
./moses/RuleCubeItem.d \
./moses/RuleCubeQueue.d \
./moses/ScoreComponentCollection.d \
./moses/ScoreComponentCollectionTest.d \
./moses/ScoreProducer.d \
./moses/Search.d \
./moses/SearchCubePruning.d \
./moses/SearchNormal.d \
./moses/SearchNormalBatch.d \
./moses/Sentence.d \
./moses/SentenceStats.d \
./moses/SourceWordDeletionFeature.d \
./moses/SparsePhraseDictionaryFeature.d \
./moses/SquareMatrix.d \
./moses/StaticData.d \
./moses/SyntacticLanguageModel.d \
./moses/TargetBigramFeature.d \
./moses/TargetBigramFeatureTest.d \
./moses/TargetNgramFeature.d \
./moses/TargetPhrase.d \
./moses/TargetPhraseCollection.d \
./moses/TargetWordInsertionFeature.d \
./moses/ThreadPool.d \
./moses/Timer.d \
./moses/TranslationOption.d \
./moses/TranslationOptionCollection.d \
./moses/TranslationOptionCollectionConfusionNet.d \
./moses/TranslationOptionCollectionText.d \
./moses/TranslationOptionList.d \
./moses/TranslationSystem.d \
./moses/TreeInput.d \
./moses/TrellisPath.d \
./moses/TrellisPathCollection.d \
./moses/UserMessage.d \
./moses/Util.d \
./moses/Word.d \
./moses/WordLattice.d \
./moses/WordTranslationFeature.d \
./moses/WordsBitmap.d \
./moses/WordsRange.d \
./moses/XmlOption.d 


# Each subdirectory must supply rules for building sources it contributes
moses/%.o: ../moses/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


