#! /bin/sh -w

bin=$1; shift
testdir=$1; shift
cd $testdir

cmd="$bin/mert --scfile data/SCORESTAT.txt --ffile data/FEATSTAT.txt --ifile data/INIT -d 14 -n 20 -r 1000"
#echo $cmd
$cmd 2>&1 | grep -i "^Best"
#echo $cmd
cmd="$bin/mert --scfile data/SCORESTAT.bin --ffile data/FEATSTAT.bin --ifile data/INIT -d 14 -n 20 -r 1000"
$cmd 2>&1 | grep -i "^Best"

