{'application':{'type':'Application',
          'name':'Extract_TMX_Corpus',
    'backgrounds': [
    {'type':'Background',
          'name':'bgExtract_TMX_Corpus',
          'title':u'Extract_TMX_Corpus',
          'size':(275, 410),
          'statusBar':1,

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileSelectDirectory',
                   'label':u'Select &input/output directory...\tCtrl+I',
                   'command':'SelectListOfDirectories',
                  },
                  {'type':'MenuItem',
                   'name':'menuGetOutputFileBaseName',
                   'label':u'Get &output file base name...\tCtrl+O',
                   'command':'GetOutputFileBaseName',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep1',
                   'label':'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExtractCorpus',
                   'label':u'&Extract corpus\tCtrl+E',
                   'command':'ExtractCorpus',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExtractSomeCorpora',
                   'label':u'Extract &some corpora\tCtrl+S',
                   'command':'ExtractSomeCorpora',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExtractAllCorpora',
                   'label':u'Extract &all corpora\tCtrl+A',
                   'command':'ExtractAllCorpora',
                  },
                  {'type':'MenuItem',
                   'name':'fileSep2',
                   'label':u'-',
                  },
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tAlt+X',
                   'command':'Doexit',
                  },
              ]
             },
             {'type':'Menu',
             'name':'menuHelp',
             'label':u'&Help',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuHelpHelp',
                   'label':u'&Help...\tCtrl+H',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'btnExtractSomeCorpora', 
    'position':(18, 267), 
    'size':(225, 25), 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 10}, 
    'label':u'Extract some corpora', 
    },

{'type':'Button', 
    'name':'btnExtractAllCorpora', 
    'position':(18, 233), 
    'size':(225, 25), 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 10}, 
    'label':u'Extract all corpora', 
    },

{'type':'StaticText', 
    'name':'StaticText3', 
    'position':(18, 107), 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 10}, 
    'text':u'Destination Language:', 
    },

{'type':'ComboBox', 
    'name':'cbDestinationLanguage', 
    'position':(18, 129), 
    'size':(225, -1), 
    'items':[], 
    },

{'type':'Button', 
    'name':'btnSelectDirectory', 
    'position':(18, 19), 
    'size':(225, 25), 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 10}, 
    'label':u'Select input / output directory...', 
    },

{'type':'ComboBox', 
    'name':'cbStartingLanguage', 
    'position':(18, 74), 
    'size':(225, -1), 
    'items':[u'DE-PT', u'EN-PT', u'ES-PT', u'FR-PT'], 
    },

{'type':'Button', 
    'name':'btnGetOutputFileBaseName', 
    'position':(18, 166), 
    'size':(225, 25), 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 10}, 
    'label':u'Select base name of output file...', 
    },

{'type':'Button', 
    'name':'btnExtractCorpus', 
    'position':(18, 200), 
    'size':(225, 25), 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 10}, 
    'label':u'Extract one corpus', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(18, 53), 
    'font':{'faceName': u'Arial', 'family': 'sansSerif', 'size': 10}, 
    'text':u'Starting Language:', 
    },

] # end components
} # end background
] # end backgrounds
} }
