#! /bin/sh -w

bin=$1; shift
testdir=$1; shift
cd $testdir

cmd="$bin/mert --scfile data/SCORESTAT.txt --ffile data/FEATSTAT.txt --ifile data/INIT -d 14 -p stdout -r 1000"
#echo $cmd
#$cmd
#echo $cmd
#cmd="$bin/mert --scfile data/SCORESTAT.bin --ffile data/FEATSTAT.bin --ifile data/INIT -p stdout -d 14 -r 1000"
$cmd

